version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/timescale:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  flask:
    build: ./API_REST
    ports:
      - "5000:5000"
    env_file:
      - database.env
    volumes:
      - ./local_data/images:/app/static/images
      
    depends_on:
      - timescaledb

    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge